FIND_PATH ( LIBCURL_INCLUDE_DIR NAMES curl PATHS /usr/include/ /usr/local/include/
    NO_DEFAULT_PATH
    NO_CMAKE_ENVIRONMENT_PATH
    NO_CMAKE_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
    NO_CMAKE_SYSTEM_PATH
    CMAKE_FIND_ROOT_PATH_BOTH
    ONLY_CMAKE_FIND_ROOT_PATH
    NO_CMAKE_FIND_ROOT_PATH
)
FIND_LIBRARY ( LIBCURL_LIBRARY NAMES curl PATHS /usr/lib /usr/local/lib ) 


IF ( LIBCURL_INCLUDE_DIR AND LIBCURL_LIBRARY )
    SET ( LIBCURL_FOUND TRUE )
ENDIF (  )


IF ( LIBCURL_FOUND )
    MESSAGE ( STATUS "Found libcurl headers in ${LIBCURL_INCLUDE_DIR}" )
    MESSAGE ( STATUS "Found libcurl library: ${LIBCURL_LIBRARY}" )
ELSE (  )
    IF ( LIBCURL_FIND_REQUIRED )
        MESSAGE ( FATAL_ERROR "Could not find libcurl" )
    ENDIF (  )
ENDIF (  )


