SET ( STOCKMARKET_PRODUCT_COMPANY_NAME "CompanyName" )
SET ( STOCKMARKET_PRODUCT_COPYRIGHT_HOLDER "CopyrightHolder" )
SET ( STOCKMARKET_PRODUCT_COPYRIGHT_YEAR "2014" )
SET ( STOCKMARKET_PRODUCT_COPYRIGHT "(C) ${STOCKMARKET_PRODUCT_COPYRIGHT_YEAR} ${STOCKMARKET_PRODUCT_COPYRIGHT_HOLDER}" )

SET ( STOCKMARKET_REST_PRODUCT_INTERNAL_NAME "StockMarketREST" )
SET ( STOCKMARKET_REST_PRODUCT_NAME "Stock Market RESTful Web Service" )
SET ( STOCKMARKET_REST_PRODUCT_VERSION_MAJOR "0" )
SET ( STOCKMARKET_REST_PRODUCT_VERSION_MINOR "1" )
SET ( STOCKMARKET_REST_PRODUCT_VERSION_PATCH "0" )
SET ( STOCKMARKET_REST_PRODUCT_DESCRIPTION "This is the RESTful web service for Stock Market" )

IF ( EXISTS "${PROJECT_SOURCE_DIR}/.git" )
    EXEC_PROGRAM ( ${GIT_EXECUTABLE}
        ARGS "--git-dir=\"${PROJECT_SOURCE_DIR}/.git\" --work-tree=\"${PROJECT_SOURCE_DIR}\" describe --always"
        OUTPUT_VARIABLE GIT_SHORT_REVISION_HASH )
    SET ( STOCKMARKET_REST_PRODUCT_VERSION_REVISION ${GIT_SHORT_REVISION_HASH} )
ELSE (  )
    SET ( STOCKMARKET_REST_PRODUCT_VERSION_REVISION "{non-git}" )
ENDIF (  )

SET ( STOCKMARKET_REST_PRODUCT_VERSION "${STOCKMARKET_REST_PRODUCT_VERSION_MAJOR}.${STOCKMARKET_REST_PRODUCT_VERSION_MINOR}.${STOCKMARKET_REST_PRODUCT_VERSION_PATCH}-${STOCKMARKET_REST_PRODUCT_VERSION_REVISION}" )


